name: build-and-publish

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5

      # JDK/Gradle
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 23
          cache: gradle
      - name: Kotlin JS Build
        run: ./gradlew compileProductionExecutableKotlinJs

      # NPM/UI
      - uses: actions/setup-node@v5
        with:
          node-version: '16'
          cache: npm
          cache-dependency-path: ./ui/package-lock.json
      - name: npm install
        run: npm install
        working-directory: ./ui
      - name: npm build
        run: npm run build
        working-directory: ./ui

      # Ship to gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ui/build
